syntax = "proto3";

package envoy.extensions.filters.http.ubpf.v3;

import "envoy/config/core/v3/base.proto";

import "udpa/annotations/status.proto";

option java_package = "io.envoyproxy.envoy.extensions.filters.http.ubpf.v3";
option java_outer_classname = "UbpfProto";
option java_multiple_files = true;
option (udpa.annotations.file_status).package_version_status = ACTIVE;

// [#protodoc-title: uBPF]
// [#extension: envoy.filters.http.ubpf]

message Ubpf {
  config.core.v3.DataSource bpf_code = 1;
}
